server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log
#- job_name: journal
#    journal:
#      max_age: 12h
#      labels:
#        job: systemd-journal
#    relabel_configs:
#      - source_labels: ['__journal__systemd_unit']
#        target_label: 'unit'
- job_name: grafana
  static_configs:
  - targets:
      - grafana
    labels:
      job: grafana
      __path__: "/var/log/grafana/grafana.log"
